title: Pseudo Nerd's Blog
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "/myblog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Shubham Upreti # add your name
author-img: logo.png # add your photo
about-author: Developer | Engineer | Freelancer
social-twitter: progmatic99 # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: progmatic-99 # add your Github handle
social-linkedin: shubham-upreti # add your Linkedin handle
social-email: shubham.upreti@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
